language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - wkhtmltopdf

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: mB495L9TTRpSCo69lqB7PWLQ9s+/S/LyfE265tyOEUhGZjx44ApbLy1Vd+qdbMH/Ij7GWIzSC3VS19Y+aVLjV0YBitN6ExFlVuFJfLQslePRa746RzYIOymJ1u6n6sPK74t8jW5R7YcKIWZkHhncrej17B/LMhqyK2AQNJw/h9U=
   
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
